/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

'use strict';

// var primeNumbers = [2,3,5,7,11];
// var index = 13;
// while(primeNumbers.length != 100) {
//   let isPrime = true;
//   for(let i = 0; i < primeNumbers.length; i++) {
//     if(index%primeNumbers[i]==0) {
//       isPrime = false;
//       break;
//     }
//   }
//   if(isPrime) {
//     primeNumbers.push(index);
//   }
//   index += 2;
// }
var num = 5984;

var biggest = 0;

while(true) {

  if(num > 94900000) {
    console.log(num);
    break;
  }
  let factors = new Array();


  let triangle = num*(num+1)/2;


  for(let i = 1; i <= triangle; i++) {
    if(triangle % i == 0) {
      factors.push(i);
    }
  }
  let len = factors.length;

  if(len >= 500) {
    break;
  }

  if(len>biggest) {
    biggest = len;
    console.log(num + ': ' + triangle + ': ' + factors.length);
  }

  if(num % 1000 == 0) {
    console.log(num + ': ' + triangle + ': ' + factors.length);

  }


  num++;

}
